### ISSUE TITLE
ratio

### ISSUE THREAD

**Issue by ormousta** [Dizeeee/catbat#2]
ratio

_Originally posted by @Dizeeee in https://github.com/Dizeeee/catbat/issues/1#issuecomment-1003132117_

**Comment by ormousta** [comment]
https://media.discordapp.net/attachments/810641714145525781/925217319398027274/3FCE3CED-9A90-4549-9E6D-67B327A57A5B.gif

**Comment by jackmalcom** [comment]
LGMT
